/*Data Sources: NHIS claim data 
Enrollment: Patients aged 39 years or older who were prescribed antidiabetic medications and had a diagnosis of diabetes mellitus (ICD-10 codes E11–E14) between 2015 and 2019.

Exclusion: Patients with a history of receiving antidiabetic medications and a diagnosis of diabetes mellitus before 2015.
data period: 2013-2023 Records*/


/* Input dataset */

/*1. Cohort construction*/
PROC SQL;
CREATE TABLE ENROLL AS SELECT A.INDI_DSCM_NO, A.CMN_KEY, A.MDCARE_STRT_DT, A.MCEX_SICK_SYM, B.MCARE_DIV_CD_ADJ, B.GROUP_MAJOR
FROM TOT.DM AS A
INNER JOIN (SELECT * FROM TOT.DRUG WHERE GROUP_MAJOR = "DM") AS B
ON A.CMN_KEY = B.CMN_KEY;
QUIT;

PROC SQL; 
CREATE TABLE ENROLL2 AS SELECT DISTINCT INDI_DSCM_NO, MIN(MDCARE_STRT_DT) AS DM_DT
FROM ENROLL
GROUP BY INDI_DSCM_NO;

CREATE TABLE ENROLL2 AS SELECT A.*, B.STD_YYYY, B.SEX_TYPE, B.BYEAR
FROM ENROLL2 AS A
LEFT JOIN TOT.BFC AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO AND SUBSTR(A.DM_DT,1,4) = B.STD_YYYY;
QUIT;
%INDI(ENROLL2); 

*Exclusion 1: DM before 2015 or under 39;
DATA ENROLL3; SET ENROLL2; 
AGE = STD_YYYY - BYEAR; 
IF AGE LT 39 THEN EXC1 = 1; ELSE EXC1 = 0;
DM_YEAR = SUBSTR(DM_DT,1,4);
IF DM_YEAR LT "2015" THEN EXC1 = 1;
RUN; 

DATA C.ENROLL; SET ENROLL3; 
IF EXC1 NE 1; RUN; 

*Enrollment2; 
PROC SQL; 
CREATE TABLE C.ENROLL AS SELECT DISTINCT *
FROM C.ENROLL AS A
INNER JOIN (SELECT DISTINCT INDI_DSCM_NO, MIN(MDCARE_STRT_DT) AS GOUT_DT 
					FROM TOT.M10 
						WHERE SUBSTR(MDCARE_STRT_DT,1,4) BETWEEN "2015" AND "2019"
					GROUP BY INDI_DSCM_NO)AS B 
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO;
QUIT;
%INDI(C.ENROLL); *230,331;

/*index date at GOUT diagnosis*/ 
DATA C.ENROLL; SET C.ENROLL; 
INDEX_DT = GOUT_DT; 
INDEX_DT1=INPUT(PUT(INDEX_DT,8.),YYMMDD8.); 
INDEX_2YBF = PUT((INDEX_DT1-730.5)+1,YYMMDDN.);
INDEX_1YBF = PUT((INDEX_DT1-365.25)+1,YYMMDDN.);
INDEX_1MAFT = PUT((INDEX_DT1+30)+1,YYMMDDN.); 
RUN;

*Exclusion2) 2013-2023 콜키친 사용가능한 상병 진단;
PROC SQL; 
CREATE TABLE C.EXC2 AS SELECT DISTINCT INDI_DSCM_NO
, MAX(P2_EXC1) AS EXC2
FROM TOT.P2_EXC
GROUP BY INDI_DSCM_NO;
QUIT;

*Exclusion 3)  MI, CAD, angina, Stroke before GOUT ;
PROC SQL;
CREATE TABLE EXC3 AS SELECT A.INDI_DSCM_NO, A.GOUT_DT, B.*
FROM C.ENROLL AS A
INNER JOIN (SELECT DISTINCT INDI_DSCM_NO, P2_EXC2, MDCARE_STRT_DT
				FROM TOT.P2_EXC) AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO
WHERE MDCARE_STRT_DT LT GOUT_DT;

CREATE TABLE C.EXC3 AS SELECT DISTINCT INDI_DSCM_NO, 1 AS EXC3 LABEL = "Previous outcome"
FROM EXC3;
QUIT;

*Exclusion 4) 2013-2023 Absolute contraindications;
PROC SQL; 
CREATE TABLE C.EXC4 AS SELECT DISTINCT INDI_DSCM_NO
, MAX(P2_EXC3) AS EXC4
FROM TOT.P2_EXC
GROUP BY INDI_DSCM_NO;
QUIT;

*Exclusion 5): Eligible data;
PROC SQL; 
CREATE TABLE EXC5 AS SELECT DISTINCT INDI_DSCM_NO, 1 AS EXC5
FROM C.ENROLL 
	WHERE AGE = . OR SEX_TYPE = "";
QUIT; *0;

%MACRO AFTDTH; 
%DO I = 2013 %TO 2023; %DO J = 1 %TO 12; %IF &J.<10 %THEN %LET K =0&J.; %ELSE %LET K=&J.;
PROC SQL;
CREATE TABLE AFTDTH_&I.&K. AS 
SELECT A.INDI_DSCM_NO, A.MDCARE_STRT_DT, B.DTH_ASSMD_DT
FROM SOURCE.claimtable_&I.&K. AS A
INNER JOIN SOURCE.death_table AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO
	WHERE A.MDCARE_STRT_DT >  B.DTH_ASSMD_DT;
	QUIT;
%END; %END;
%MEND; 
%AFTDTH;
DATA C.EXC5; SET AFTDTH_:; RUN; 

PROC SQL; 
CREATE TABLE C.EXC5 AS SELECT DISTINCT INDI_DSCM_NO, 1 AS EXC5
FROM C.EXC5; 
QUIT; *364;

*Exclusion 9) Patients without use of other gout medications; 
PROC SQL; 
CREATE TABLE C.EXC9 AS SELECT DISTINCT INDI_DSCM_NO, 0 AS EXC9 LABEL = "Other gout medication", MDCARE_STRT_DT, MCARE_DIV_CD_ADJ, GROUP_MAJOR
FROM (SELECT * FROM TOT.DRUG 
		WHERE GROUP_MAJOR = "GOUT" AND MCARE_DIV_CD_ADJ NE "GOUT");
QUIT;

PROC SQL; 
CREATE TABLE C.EXC9 AS SELECT DISTINCT INDI_DSCM_NO, EXC9
FROM C.EXC9; QUIT;
%indi(exc9); *107,272;

*JOIN; 
%MACRO JOIN;
%DO I = 2 %TO 9;
PROC SQL; 
CREATE TABLE C.ENROLL AS SELECT * FROM C.ENROLL AS A
LEFT JOIN C.EXC&I. AS B
ON A.INDI_DSCM_NO= B.INDI_DSCM_NO;
QUIT;
%END; %MEND;
%JOIN;

PROC STDIZE DATA=C.ENROLL OUT=C.ENROLL
REPONLY MISSING=0; VAR EXC2 EXC3 EXC4 EXC5 EXC6 EXC7 EXC9; RUN;


/*Group non user vs colchicin user:
Patients who received colchicine at least once or for ≥90 days between 2015 and 2023*/
PROC SQL; 
CREATE TABLE C.COL_USER AS SELECT A.INDI_DSCM_NO, A.GOUT_DT, B.MDCARE_STRT_DT, B.TOT_MCNT, B.MCARE_DIV_CD_ADJ
FROM C.ENROLL AS A
INNER JOIN (SELECT * FROM TOT.DRUG 
				WHERE MCARE_DIV_CD_ADJ IN ("GOUT") AND SUBSTR(MDCARE_STRT_DT,1,4) GE "2015")AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO
ORDER BY INDI_DSCM_NO, MDCARE_STRT_DT;
QUIT;

*at least once;
PROC SQL; 
CREATE TABLE GROUP AS SELECT DISTINCT INDI_DSCM_NO, GOUT_DT, 1 AS COL_ONCE, MIN(MDCARE_STRT_DT) AS COL_DT
FROM C.COL_USER
GROUP BY INDI_DSCM_NO;
QUIT;
%INDI(C.COL_USER); *58,432: 15-23 at least once;

*≥90 days; 
PROC SQL;
CREATE TABLE COL2 AS SELECT DISTINCT INDI_DSCM_NO, MDCARE_STRT_DT, MAX(TOT_MCNT) AS M_MCNT
FROM C.COL_USER 
GROUP BY INDI_DSCM_NO, MDCARE_STRT_DT;

CREATE TABLE COL3 AS SELECT DISTINCT INDI_DSCM_NO, SUM(M_MCNT) AS COL_MCNT
FROM COL2
GROUP BY INDI_DSCM_NO;

CREATE TABLE COL4 AS SELECT DISTINCT *
,(CASE WHEN COL_MCNT GE 90 THEN 1 ELSE 0 END) AS COL_90
FROM COL3; 
QUIT;

PROC SQL; 
CREATE TABLE C.ENROLL AS SELECT *
FROM C.ENROLL AS A
LEFT JOIN GROUP AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO
LEFT JOIN COL4 AS C
ON A.INDI_DSCM_NO = C.INDI_DSCM_NO;
QUIT;

PROC STDIZE DATA=C.ENROLL OUT=C.ENROLL
MISSING=0 REPONLY; VAR COL_90 COL_ONCE; RUN;

DATA C.ENROLL; SET C.ENROLL; 
IF COL_DT NE "" AND COL_DT LT GOUT_DT THEN EXC6 = 1; ELSE EXC6 = 0; RUN;


/*=====================================================
2. Covariate definition
=====================================================*/
 /*CCI: 3 categorical (0, 1, over 2)*/
* Restricted to inpatient records within 1 year before the index date;
* Only the primary diagnosis and first secondary diagnosis were considered;
* Comorbidity scores were assigned using the updated Charlson Comorbidity Index weighting scheme, and the total score was calculated by summing the individual disease weights;

proc sql;
create table cci_tot_index as
select distinct a.*, INPUT(B.INDEX_DT,YYMMDD8.)-input(A.mdcare_strt_dt, yymmdd8.) as dif, b.INDEX_DT
from tot.cci_tot as a inner join C.enroll as b
on a.indi_dscm_no=b.indi_dscm_no
having 0 le dif le 365;
quit;
proc sort data=cci_tot_index; by indi_dscm_no mdcare_strt_dt; run; 

proc sql; 
create table cci_tot_index as select * from cci_tot_index 
	where form_cd in ("02" "07" "09" "10"); 
quit;

proc sql; 
create table cci_tot_index2 as select distinct indi_dscm_no, max(cnt_cci1) as cci1, max(cnt_cci2) as cci2, max(cnt_cci3) as cci3, max(cnt_cci4) as cci4, max(cnt_cci5) as cci5, max(cnt_cci6) as cci6
, max(cnt_cci7) as cci7, max(cnt_cci8) as cci8, max(cnt_cci9) as cci9, max(cnt_cci10) as cci10, max(cnt_cci11) as cci11, max(cnt_cci12) as cci12, max(cnt_cci13) as cci13
, max(cnt_cci14) as cci14, max(cnt_cci15) as cci15, max(cnt_cci16) as cci16, max(cnt_cci17) as cci17
from cci_tot_index
group by indi_dscm_no;
quit;

data cci_tot_index2; set cci_tot_index2; 
if cci11 = 1 then cci10= .; run; 
proc stdize data=cci_tot_index2 out=cci_tot_index2 missing=0 reponly; var cci:; run;

*updated weight;
data C.cci_tot_score; set cci_tot_index2; 
CCI=(cci1*0+cci2*2+cci3*0+cci4*0+cci5*2+cci6+cci7+cci8*0+cci9*2+cci10*0+cci11
+cci12*2+cci13+cci14*2+cci15*6+cci16*4+cci17*4); run;
proc means data=C.cci_tot_score min max mean std; var cci; run; 

*join;
proc sql;
create table C.ENROLL as select A.*, B.CCI from C.ENROLL as a left join 
C.cci_tot_score as b
on a.indi_dscm_no=b.indi_dscm_no;
quit;

proc stdize data=C.ENROLL out=C.ENROLL missing=0 reponly; var cci; run;
DATA C.ENROLL; SET C.ENROLL; 
IF CCI = 0 THEN CCI_GR = 0;
IF CCI = 1 THEN CCI_GR = 1; 
IF CCI GE 2 THEN CCI_GR = 2; 
RUN;

*6-3) CVD history befoer 1 year Index date;
%MACRO CVD(VAR, I);
PROC SQL;
CREATE TABLE CVD&I. AS SELECT *
FROM C.ENROLL AS A
INNER JOIN TOT.&VAR. AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO
	WHERE MDCARE_STRT_DT LT INDEX_DT AND MDCARE_STRT_DT GE INDEX_1YBF
	ORDER BY INDI_DSCM_NO, MDCARE_STRT_DT; 

CREATE TABLE C.CVD&I. AS SELECT DISTINCT INDI_DSCM_NO, 1 AS CVD&I.
FROM CVD&I.;
QUIT;
%MEND;
%CVD(MI,1); *CVD 1: Myocardial infarction	I21, I22 with hospitalization AND I25.2;
%CVD(PCI,2); *CVD2: PCI 	M6551, M6552, M6561, M6562, M6563, M6564, M6565, M6566, M6567;
%CVD(HF,3); *CVD3: Heart failure	I43, I50, I099, I110, I130, I132, I255, I420, I425, I426, I427, I428, I429, P290;

*CVD4 Hemorrhagic	I60-I62;
PROC SQL;
CREATE TABLE HEMO_STR AS SELECT * 
FROM TOT.STR
	WHERE HEMORRHAGIC = 1; 


CREATE TABLE C.CVD4 AS SELECT DISTINCT INDI_DSCM_NO, 1 AS CVD4
FROM (SELECT A.*, B.INDI_DSCM_NO, B.INDEX_DT
			FROM HEMO_STR  AS A
			INNER JOIN C.ENROLL AS B
			ON A.INDI_DSCM_NO = B.INDI_DSCM_NO
				WHERE MDCARE_STRT_DT LT INDEX_DT AND MDCARE_STRT_DT GE INDEX_1YBF);
QUIT;

*CVD5  Ischemic	I63-I64;
PROC SQL;
CREATE TABLE ISCHEMIC_STR AS SELECT * 
FROM TOT.STR
	WHERE ISCHEMIC = 1; 

CREATE TABLE C.CVD5 AS SELECT DISTINCT INDI_DSCM_NO, 1 AS CVD5
FROM (SELECT A.*, B.INDI_DSCM_NO, B.INDEX_DT
			FROM ISCHEMIC_STR  AS A
			INNER JOIN C.ENROLL AS B
			ON A.INDI_DSCM_NO = B.INDI_DSCM_NO
				WHERE MDCARE_STRT_DT LT INDEX_DT AND MDCARE_STRT_DT GE INDEX_1YBF);
QUIT;

*6-4) Comorbidities	before 1 year index date;
%MACRO COMO(VAR, I);
PROC SQL;
CREATE TABLE COMO&I. AS SELECT A.INDI_DSCM_NO, A.INDEX_DT, A.INDEX_1YBF, B.*
FROM C.ENROLL AS A
INNER JOIN TOT.&VAR. AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO
	WHERE MDCARE_STRT_DT LT INDEX_DT AND MDCARE_STRT_DT GE INDEX_1YBF
	ORDER BY INDI_DSCM_NO, MDCARE_STRT_DT; 

CREATE TABLE C.COMO&I. AS SELECT DISTINCT INDI_DSCM_NO, 1 AS COMO&I.
FROM COMO&I.;
QUIT;
%MEND;
%COMO(DM,1); *COMO1: Diabetes	E11-E14 at least once;
%COMO(HTN, 2); *COMO2: 	Hypertension	I10-I13, I15;
%COMO(DYSLIPID,3); *COMO3: 	Dylipidemia	E78 (E786, E788, E789 exclude) AND statin;
PROC SQL;
CREATE TABLE COMO3_1 AS SELECT *
FROM COMO3 AS A
INNER JOIN (SELECT * FROM TOT.DRUG
					WHERE MCARE_DIV_CD_ADJ IN ("Antilipidemic")) AS B
ON A.CMN_KEY =B.CMN_KEY;
QUIT;

PROC SQL;
CREATE TABLE C.COMO3 AS SELECT DISTINCT INDI_DSCM_NO, 1 AS COMO3
FROM COMO3_1;
QUIT;

%COMO(PULMO,4); *COMO4: pulmonary	J40, J41, J42, J43, J44, J45, J46, J47, J60, J61, J62, J63, J64, J65, J66, J67, I278, I279, J684, J701, J703; 
%COMO(LIVER,5); *COMO5: liver	K704, K711, K721, K729, K765, K766, K767, I850, I859, I864, I982;
%COMO(RENAL,6); *COMO6: renal N18, N19, I120, I131, N032, N033, N034, N035, N036, N037, N052, N053, N054, N055, N056, N057, N250, Z490, Z491 Z492, Z940, Z992;

*COMO7: ESRD	O7020, O9991, O7061, O7062, O7071-O7074 산정특례 V001, V003, V005;
PROC SQL;
CREATE TABLE COMO7_V AS SELECT A.INDI_DSCM_NO, A.INDEX_DT, A.INDEX_1YBF, B.*
FROM C.ENROLL AS A
INNER JOIN TOT.ESRD_VCODE AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO
	WHERE MDCARE_STRT_DT LT INDEX_DT AND MDCARE_STRT_DT GE INDEX_1YBF
	ORDER BY INDI_DSCM_NO, MDCARE_STRT_DT; 

CREATE TABLE COMO7_PC AS SELECT A.INDI_DSCM_NO, A.INDEX_DT, A.INDEX_1YBF, B.*
FROM C.ENROLL AS A
INNER JOIN TOT.ESRD_PROCEDURE AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO
	WHERE MDCARE_STRT_DT LT INDEX_DT AND MDCARE_STRT_DT GE INDEX_1YBF
	ORDER BY INDI_DSCM_NO, MDCARE_STRT_DT; 
QUIT;
DATA COMO7; SET COMO7_V COMO7_PC; RUN; 
PROC SQL;
CREATE TABLE C.COMO7 AS SELECT DISTINCT INDI_DSCM_NO, 1 AS COMO7
FROM COMO7;
QUIT;

%COMO(BRAIN,8); *COMO8:	cerebrovasculart	G45, G46, I60, I61, I62, I63, I64, I65, I66, I67, I68, I69, H340;
%COMO(PAD,9); *COMO9:	pheriperal	I70-I71, I731, I738, I739, I771, I790, I792, K551, K558, K559, Z958, Z959;

*COMO10: cancer	C코드, 산정특례 V027, V193, V194;
PROC SQL;
CREATE TABLE COMO10_CODE AS SELECT A.INDI_DSCM_NO, A.INDEX_DT, A.INDEX_1YBF, B.*
FROM C.ENROLL AS A
INNER JOIN TOT.CANCER AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO
	WHERE MDCARE_STRT_DT LT INDEX_DT AND MDCARE_STRT_DT GE INDEX_1YBF
	ORDER BY INDI_DSCM_NO, MDCARE_STRT_DT; 

CREATE TABLE COMO10_V AS SELECT A.INDI_DSCM_NO, A.INDEX_DT, A.INDEX_1YBF, B.*
FROM C.ENROLL AS A
INNER JOIN TOT.CANCER_VCODE AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO
	WHERE MDCARE_STRT_DT LT INDEX_DT AND MDCARE_STRT_DT GE INDEX_1YBF
	ORDER BY INDI_DSCM_NO, MDCARE_STRT_DT; 
QUIT;
DATA COMO10; SET COMO10_CODE COMO10_V; RUN; 
PROC SQL;
CREATE TABLE C.COMO10 AS SELECT DISTINCT INDI_DSCM_NO, 1 AS COMO10
FROM COMO10;
QUIT;

%COMO(VALVE,11); *COMO11:Valve	I05-I09, I34-I39;
%COMO(ARRHYTHM,12) *COMO12: Arrythm	I47-I49;
%COMO(AFIB,13); *COMO13: Atrial fibrillation/flutter	I48.0-48.4, I48.9;


%MACRO JOIN;
%DO I= 1 %TO 5; 
PROC SQL;
CREATE TABLE C.ENROLL AS SELECT * 
FROM C.ENROLL AS A
LEFT JOIN C.CVD&I. AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO;
QUIT;
%END;

%DO I= 1 %TO 13; 
PROC SQL;
CREATE TABLE C.ENROLL AS SELECT * 
FROM C.ENROLL AS A
LEFT JOIN C.COMO&I. AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO;
QUIT;
%END; 
%MEND; 
%JOIN; 

PROC STDIZE DATA=C.ENROLL OUT=C.ENROLL
REPONLY MISSING=0; VAR CVD: COMO:; RUN; 

*6-5) * The laboratory value closest to the index date was selected from all available measurements before the index date
* Evaluated only among patients with available linked health examination data;
DATA LAB; SET C.ENROLL(KEEP=INDI_DSCM_NO INDEX_DT); RUN;

%MACRO LAB(N, VAR1, VAR2, VAR3);
%DO I = 2013 %TO 2017;
PROC SQL; 
CREATE TABLE LAB&N._&I. AS SELECT *
FROM LAB AS A
INNER JOIN (SELECT INDI_DSCM_NO, HME_DT, &VAR1. FROM SOURCE.gumjin_table&I.) AS B
ON A.INDI_DSCM_NO= B.INDI_DSCM_NO
ORDER BY INDI_DSCM_NO, HME_DT;
QUIT;
%END;

PROC SQL; 
CREATE TABLE LAB&N._2018 AS SELECT *
FROM LAB AS A
INNER JOIN (SELECT INDI_DSCM_NO, HME_DT, &VAR2. AS &VAR1. FROM SOURCE.gumjin_table_2018) AS B
ON A.INDI_DSCM_NO= B.INDI_DSCM_NO
ORDER BY INDI_DSCM_NO, HME_DT;
QUIT;

%DO I = 2019 %TO 2023;
PROC SQL; 
CREATE TABLE LAB&N._&I. AS SELECT *
FROM LAB AS A
INNER JOIN (SELECT INDI_DSCM_NO, HC_DT AS HME_DT, &VAR3. AS &VAR1. FROM SOURCE.gumjin_table_&I.) AS B
ON A.INDI_DSCM_NO= B.INDI_DSCM_NO
ORDER BY INDI_DSCM_NO, HME_DT;
QUIT;
%END; 
 %MEND;
 %LAB(1, G1E_FBS, G1E_FBS,G1E_FBS); 
%LAB(2, G1E_TOT_CHOL, G1E_TOT_CHOL,G1E_TOT_CHOL);
%LAB(3, G1E_LDL_CALC, G1E_LDL_CALC,G1E_LDL_CALC);
%LAB(4, G1E_HDL, G1E_HDL,G1E_HDL);
%LAB(5, G1E_TG, G1E_TG, G1E_TG);
%LAB(6, G1E_HGHT,G1E_HGHT,G1E_HGHT );
%LAB(7, G1E_WGHT, G1E_WGHT, G1E_WGHT);
%LAB(8, G1E_WSTC,G1E_WSTC,G1E_WSTC);
%LAB(9, G1E_BP_SYS, G1E_BP_SYS, G1E_BP_SYS); 
%LAB(10, G1E_BP_DIA, G1E_BP_DIA, G1E_BP_DIA);
%LAB(11, G1E_SGOT, G1E_SGOT, G1E_SGOT);
%LAB(12, G1E_SGPT, G1E_SGPT, G1E_SGPT);
%LAB(13, G1E_GGT, G1E_GGT, G1E_GGT);

%MACRO LABB(N, VAR); *before index (no missing);
DATA LAB&N.; SET LAB&N._:; IF HME_DT LE INDEX_DT AND &VAR. NE .; RUN; 

PROC SORT DATA=LAB&N.; BY INDI_DSCM_NO HME_DT; RUN; 

PROC SQL;
CREATE TABLE LAB&N._2 AS SELECT DISTINCT INDI_DSCM_NO, INDEX_DT, HME_DT, MAX(HME_DT) AS STD_DT, &VAR.
FROM LAB&N.
GROUP BY INDI_DSCM_NO;

CREATE TABLE C.LAB&N. AS SELECT DISTINCT INDI_DSCM_NO, &VAR. AS LAB&N.
FROM LAB&N._2
	WHERE STD_DT = HME_DT; 
QUIT;
%MEND; 
%LABB(1, G1E_FBS);
%LABB(2, G1E_TOT_CHOL);
%LABB(3, G1E_LDL_CALC);
%LABB(4, G1E_HDL);
%LABB(5, G1E_TG);
%LABB(6, G1E_HGHT);
%LABB(7, G1E_WGHT); 
%LABB(8, G1E_WSTC);
%LABB(9, G1E_BP_SYS); 
%LABB(10, G1E_BP_DIA);
%LABB(11, G1E_SGOT);
%LABB(12, G1E_SGPT);
%LABB(13, G1E_GGT);

/*Questionnaire*/
%MACRO QLAB(N, VAR1, VAR2, VAR3);
%DO I = 2013 %TO 2017;
PROC SQL; 
CREATE TABLE LAB&N._&I. AS SELECT *
FROM LAB AS A
INNER JOIN (SELECT INDI_DSCM_NO, HME_DT, &VAR1. FROM SOURCE.qtable_&I.) AS B
ON A.INDI_DSCM_NO= B.INDI_DSCM_NO
ORDER BY INDI_DSCM_NO, HME_DT;
QUIT;
%END;

PROC SQL; 
CREATE TABLE LAB&N._2018 AS SELECT *
FROM LAB AS A
INNER JOIN (SELECT INDI_DSCM_NO, HME_DT, &VAR2. AS &VAR1. FROM SOURCE.qtable_2018) AS B
ON A.INDI_DSCM_NO= B.INDI_DSCM_NO
ORDER BY INDI_DSCM_NO, HME_DT;
QUIT;

%DO I = 2019 %TO 2023;
PROC SQL; 
CREATE TABLE LAB&N._&I. AS SELECT *
FROM LAB AS A
INNER JOIN (SELECT INDI_DSCM_NO, HC_DT AS HME_DT, &VAR3. AS &VAR1. FROM SOURCE.qtable_&I.) AS B
ON A.INDI_DSCM_NO= B.INDI_DSCM_NO
ORDER BY INDI_DSCM_NO, HME_DT;
QUIT;
%END; 
 %MEND;

 *LAB14: Smoking	1. Non-smoker or ex-smoker  2. Current smoker;
%QLAB(14, Q_SMK_YN, Q_SMK_YN, Q_SMK_NOW_YN);

%MACRO SMK_ORG;
%DO I = 2013 %TO 2018;
DATA  LAB14_&I.; SET  LAB14_&I.; 
IF Q_SMK_YN = 1  OR Q_SMK_YN = 2 THEN LAB14 = 0; ELSE LAB14 = 1;
IF Q_SMK_YN = . THEN LAB14 = .;
%END;

%DO I = 2019 %TO 2023;
DATA  LAB14_&I.; SET  LAB14_&I.; 
IF Q_SMK_YN = 1  THEN LAB14 = 1;ELSE LAB14 = 0;
IF Q_SMK_YN = . THEN LAB14 = .;
RUN;
%END; 
 %MEND;
%SMK_ORG;

%MACRO QLABB(N); *before Index(no missing );
DATA LAB&N.; SET LAB&N._:; IF HME_DT LE INDEX_DT AND LAB&N. NE .; RUN; 

PROC SORT DATA=LAB&N.; BY INDI_DSCM_NO HME_DT; RUN; 

PROC SQL;
CREATE TABLE LAB&N._2 AS SELECT DISTINCT INDI_DSCM_NO, INDEX_DT, HME_DT, MAX(HME_DT) AS STD_DT, LAB&N.
FROM LAB&N.
GROUP BY INDI_DSCM_NO;

CREATE TABLE C.LAB&N. AS SELECT DISTINCT INDI_DSCM_NO, LAB&N.
FROM LAB&N._2
	WHERE STD_DT = HME_DT; 
QUIT;
%MEND; 
%QLABB(14);

 *LAB15:alchohol	1. None  2. ≥1 time/week

%QLAB(15, Q_DRK_FRQ_V09N, Q_DRK_PER, Q_DRK_PER);
%MACRO DRK_ORG;
%DO I = 2013 %TO 2017;
DATA LAB15_&I.; SET LAB15_&I.; IF Q_DRK_FRQ_V09N = 0 THEN LAB15 = 0; ELSE LAB15 = 1; 
IF Q_DRK_FRQ_V09N = . THEN LAB15 = .; RUN; 
%END;

%DO I = 2018 %TO 2023;
DATA LAB15_&I.; SET LAB15_&I.; IF Q_DRK_FRQ_V09N = 4 THEN LAB15 = 0; ELSE LAB15 = 1; 
IF Q_DRK_FRQ_V09N = . THEN LAB15 = .; RUN; 
RUN; 
%END; 
 %MEND;
%DRK_ORG;
%QLABB(15);

*LAB16 PA	1. None  2. ≥1 time/week;
%MACRO PA_ORG(N);
%DO I = 2013 %TO 2017;
PROC SQL; 
CREATE TABLE LAB&N._&I. AS SELECT *
FROM LAB AS A
INNER JOIN (SELECT INDI_DSCM_NO, HME_DT, Q_PA_MD, Q_PA_VD FROM SOURCE.gumjin_table_&I.
				WHERE Q_PA_MD NE . OR Q_PA_VD NE .) AS B
ON A.INDI_DSCM_NO= B.INDI_DSCM_NO
ORDER BY INDI_DSCM_NO, HME_DT;
QUIT;

DATA  LAB&N._&I.; SET LAB&N._&I.;
IF Q_PA_MD = 0 AND Q_PA_VD = 0 THEN LAB16 = 0; ELSE LAB16 = 1; RUN;
%END;

PROC SQL; 
CREATE TABLE LAB&N._2018 AS SELECT *
FROM LAB AS A
INNER JOIN (SELECT INDI_DSCM_NO, HME_DT, Q_PA_MD_FRQ, Q_PA_VD_FRQ FROM SOURCE.gumjin_table_2018
			WHERE Q_PA_MD_FRQ NE . OR Q_PA_VD_FRQ NE .) AS B
ON A.INDI_DSCM_NO= B.INDI_DSCM_NO
ORDER BY INDI_DSCM_NO, HME_DT;
QUIT;

DATA  LAB&N._2018; SET LAB&N._2018;
IF Q_PA_MD_FRQ = 0 AND Q_PA_VD_FRQ = 0 THEN LAB16 = 0; ELSE LAB16 = 1; RUN;

%DO I = 2019 %TO 2023;
PROC SQL; 
CREATE TABLE LAB&N._&I. AS SELECT *
FROM LAB AS A
INNER JOIN (SELECT INDI_DSCM_NO, HC_DT AS HME_DT, Q_PA_MD_FRQ, Q_PA_VD_FRQ FROM SOURCE.qtable_&I.
			WHERE Q_PA_MD_FRQ NE . OR Q_PA_VD_FRQ NE .) AS B
ON A.INDI_DSCM_NO= B.INDI_DSCM_NO
ORDER BY INDI_DSCM_NO, HME_DT;
QUIT;


DATA  LAB&N._&I.; SET LAB&N._&I.;
IF Q_PA_MD_FRQ = 0 AND Q_PA_VD_FRQ = 0 THEN LAB16 = 0; ELSE LAB16 = 1; RUN;
%END; 
%MEND;
%PA_ORG(16);
%QLABB(16);

%MACRO DUPCHK;
%DO I = 1 %TO 16;
proc sql; select distinct indi_dscm_no, count(*) as tt from C.LAB&I. group by 1
having tt>1; quit;

%END;
%mend;
%DUPCHK;

DATA C.LAB16; SET C.LAB16; 
IF INDI_DSCM_NO = "  " AND LAB16 = 0 THEN DELETE; RUN; 
%MACRO JOIN;
%DO I= 1 %TO 16; 
PROC SQL;
CREATE TABLE C.ENROLL AS SELECT * 
FROM C.ENROLL AS A
LEFT JOIN C.LAB&I. AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO;
QUIT;
%END;
%MEND;
%JOIN; 


/*Outcome definition*/
*Outcome 1: all cause death; 
PROC SQL; 
CREATE TABLE OUT1 AS SELECT A.INDI_DSCM_NO, A.INDEX_DT,  B.*	
FROM C.ENROLL AS A
INNER JOIN SOURCE.death_table AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO
	WHERE B.DTH_ASSMD_DT GE INDEX_DT AND B.DTH_ASSMD_DT LE "20231231";
	
CREATE TABLE C.OUT1 AS SELECT DISTINCT INDI_DSCM_NO, 1 AS OUT1, DTH_ASSMD_DT AS OUT1_DT
FROM OUT1;
QUIT; *124,538;

*Outcome 2: cv death; 
PROC SQL; 
CREATE TABLE OUT2 AS SELECT *
FROM OUT1  AS A
INNER JOIN (SELECT * FROM SOURCE.FINAL_COD_DB 
				WHERE SUBSTR(DTH_CODE1,1,1) IN ("I"))AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO_M;

CREATE TABLE C.OUT2 AS SELECT DISTINCT INDI_DSCM_NO, 1 AS OUT2, DTH_ASSMD_DT AS OUT2_DT, DTH_CODE1
FROM OUT2;
QUIT; *18110;

*OUT3 * Stroke (hemorrhagic or ischemic): hospitalization for ICD-10 codes I60–I64 with brain CT or MRI;
PROC SQL; 
CREATE TABLE STR AS SELECT DISTINCT A.INDI_DSCM_NO, A.CMN_KEY, A.MDCARE_STRT_DT, A.MCEX_SICK_SYM, B.MCARE_DIV_CD_ADJ, A.FORM_CD
FROM (SELECT * FROM TOT.STR 
				WHERE FORM_CD IN ("02", "07", "09", "10")) AS A
INNER JOIN TOT.BRAIN_PC AS B
ON A.CMN_KEY = B.CMN_KEY;

CREATE TABLE STR AS SELECT A.INDI_DSCM_NO, A.INDEX_DT, B.MDCARE_STRT_DT, B.MCEX_SICK_SYM, B.FORM_CD, B.MCARE_DIV_CD_ADJ
FROM C.ENROLL AS A
INNER JOIN STR AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO
	WHERE MDCARE_STRT_DT GE INDEX_DT; 

CREATE TABLE C.OUT3 AS SELECT DISTINCT INDI_DSCM_NO, 1 AS OUT3, MIN(MDCARE_STRT_DT) AS OUT3_DT
FROM STR
GROUP BY INDI_DSCM_NO; *58,743;
QUIT;

* OUT4: Hospitalization for myocardial infarction (ICD-10 codes I21–I23) based on primary or secondary diagnosis;
DATA MI; SET TOT.OUTCOME_MI;
IF FORM_CD IN ("02", "07", "09", "10");
IF SUBSTR(SICK_SYM1,1,3) IN ("I21", "I22", "I23") OR SUBSTR(SICK_SYM2,1,3) IN ("I21", "I22", "I23");
RUN; 

PROC SQL; 
CREATE TABLE MI AS SELECT A.INDI_DSCM_NO, A.INDEX_DT, B.MDCARE_STRT_DT, B.MCEX_SICK_SYM, B.FORM_CD 
FROM C.ENROLL AS A
INNER JOIN MI AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO
	WHERE MDCARE_STRT_DT GE INDEX_DT; 

CREATE TABLE C.OUT4 AS SELECT DISTINCT INDI_DSCM_NO, 1 AS OUT4, MIN(MDCARE_STRT_DT) AS OUT4_DT
FROM MI
GROUP BY INDI_DSCM_NO; *20539;
QUIT;

/*OUT5	Composite MACE	0: non, 1: yes	CV Death, MI, Stroke */
PROC SQL; 
CREATE TABLE OUT5 AS SELECT * FROM C.OUT2
UNION ALL SELECT  * FROM C.OUT4
UNION ALL SELECT * FROM C.OUT3;
QUIT;

PROC SQL; 
CREATE TABLE C.OUT5 AS SELECT DISTINCT INDI_DSCM_NO, 1 AS OUT5, MIN(OUT2_DT) AS OUT5_DT 
FROM OUT5
GROUP BY INDI_DSCM_NO;
QUIT; *88146;

/*OUT6: Composite MACE All cause death, MI, Stroke*/
PROC SQL; 
CREATE TABLE OUT6 AS SELECT * FROM C.OUT1
UNION ALL SELECT  * FROM C.OUT4
UNION ALL SELECT * FROM C.OUT3;
QUIT;

PROC SQL; 
CREATE TABLE C.OUT6 AS SELECT DISTINCT INDI_DSCM_NO, 1 AS OUT6, MIN(OUT1_DT) AS OUT6_DT 
FROM OUT6
GROUP BY INDI_DSCM_NO;
QUIT; *180,562;


* OUT7: Additional myocardial infarction outcome, defined as hospitalization for ≥3 days with a primary diagnosis of myocardial infarction (ICD-10 codes I21–I22), occurring at least 30 days after the index date;PROC SQL;
CREATE TABLE OUT7 AS SELECT DISTINCT A.INDI_DSCM_NO, A.INDEX_DT, A.INDEX_1MAFT, B.*
FROM C.ENROLL AS A
INNER JOIN C.OUT4 AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO
	WHERE B.OUT4_DT GE INDEX_1MAFT;
QUIT;

PROC SQL; 
CREATE TABLE C.OUT7 AS SELECT DISTINCT INDI_DSCM_NO, OUT4_DT AS OUT7_DT, 1 AS OUT7
FROM OUT7;
QUIT;

*JOIN; 
%MACRO JOIN;
%DO I = 1 %TO 7;
PROC SQL; 
CREATE TABLE C.ENROLL AS SELECT * FROM C.ENROLL AS A
LEFT JOIN C.OUT&I. AS B
ON A.INDI_DSCM_NO= B.INDI_DSCM_NO;
QUIT;
%END; %MEND;
%JOIN;

PROC STDIZE DATA=C.ENROLL OUT=C.ENROLL
MISSING=0 REPONLY; VAR OUT1 OUT2 OUT3 OUT4 OUT5 OUT6;
QUIT;

*DURATION;
%MACRO TDUR;
%DO I = 7 %TO 7;
DATA C.ENROLL; SET C.ENROLL;
IF OUT&I. = 1 THEN TDUR&I. = (INPUT(OUT&I._DT,YYMMDD8.)-INPUT(INDEX_DT,YYMMDD8.))/365.25; 
ELSE IF OUT&I. = 0 AND OUT1 =1 THEN TDUR&I. = (INPUT(OUT1_DT,YYMMDD8.)-INPUT(INDEX_DT,YYMMDD8.))/365.25;
ELSE IF OUT&I. = 0 AND OUT1 =0 THEN TDUR&I. = (INPUT("20231231",YYMMDD8.)-INPUT(INDEX_DT,YYMMDD8.))/365.25;
RUN; 
%END;
%MEND;
%TDUR; 

* Exclusion 6: Patients who experienced an outcome after gout diagnosis but before initiation of colchicine therapy;
PROC SQL; 
CREATE TABLE EXC7 AS SELECT DISTINCT INDI_DSCM_NO, OUT1_DT AS EXC7_DT, OUT1 AS EXC7 FROM C.OUT1
UNION ALL SELECT DISTINCT INDI_DSCM_NO, OUT2_DT AS EXC7_DT, OUT2 AS EXC7 FROM C.OUT2
UNION ALL SELECT DISTINCT INDI_DSCM_NO, OUT3_DT AS EXC7_DT, OUT3 AS EXC7 FROM C.OUT3
UNION ALL SELECT DISTINCT INDI_DSCM_NO, OUT4_DT AS EXC7_DT, OUT4 AS EXC7 FROM C.OUT4
UNION ALL SELECT DISTINCT INDI_DSCM_NO, OUT5_DT AS EXC7_DT, OUT5 AS EXC7 FROM C.OUT5
UNION ALL SELECT DISTINCT INDI_DSCM_NO, OUT6_DT AS EXC7_DT, OUT6 AS EXC7 FROM C.OUT6
ORDER BY INDI_DSCM_NO; QUIT;

PROC SQL; 
CREATE TABLE EXC7 AS SELECT DISTINCT INDI_DSCM_NO, MIN(EXC7_DT) AS EXC7_DT, 1 AS EXC7
FROM EXC7
GROUP BY INDI_DSCM_NO;
QUIT;

PROC SQL; 
CREATE TABLE C.EXC7 AS SELECT DISTINCT A.INDI_DSCM_NO, A.COL_DT, B.*
FROM C.ENROLL AS A
INNER JOIN EXC7 AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO
	WHERE EXC7_DT LT COL_DT;
QUIT; *484;

PROC SQL; 
CREATE TABLE C.ENROLL AS SELECT DISTINCT *
FROM C.ENROLL AS A
LEFT JOIN C.EXC7 AS B
ON A.INDI_DSCM_NO= B.INDI_DSCM_NO;
QUIT;


/*Medication*/
PROC SQL; 
CREATE TABLE TOT.DRUG_GRP AS SELECT A.INDI_DSCM_NO, A.MDCARE_STRT_DT, A.MCARE_DIV_CD_ADJ, B.*
FROM TOT.DRUG AS A
INNER JOIN DRUG AS B
ON A.MCARE_DIV_CD_ADJ = B.F1;
QUIT;

PROC SQL; 
CREATE TABLE DRUG2 AS SELECT A.INDI_DSCM_NO, B.*
FROM C.ENROLL AS A
INNER JOIN TOT.DRUG_GRP AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO
ORDER BY INDI_DSCM_NO, MDCARE_STRT_DT;

CREATE TABLE C.MEDI AS SELECT DISTINCT INDI_DSCM_NO
,MAX(NOAC) AS MEDI1
,MAX(Warfarin) AS MEDI2
,MAX(Antilipidemic) AS MEDI3
, MAX(ARB) AS MEDI4
,MAX(Aspirin) AS MEDI5
,MAX(Clopidogrel) AS MEDI6
,MAX(Antiplatelet) AS MEDI7
,MAX(P2Y12) AS MEDI8
,MAX(SGLT2) AS MEDI9
,MAX(ACEI) AS MEDI10
,MAX(Diuretics) AS MEDI11
,MAX(b_blocker) AS MEDI12
FROM DRUG2
GROUP BY INDI_DSCM_NO;
QUIT;

PROC SQL; 
CREATE TABLE C.ENROLL AS SELECT * FROM C.ENROLL AS A
LEFT JOIN C.MEDI AS B
ON A.INDI_DSCM_NO = B.INDI_DSCM_NO;
QUIT;

PROC STDIZE DATA=C.ENROLL OUT=C.ENROLL
MISSING=0 REPONLY; VAR MEDI:;
QUIT;

/*PSM*/
/*FLOW CHART*/
DATA C.FINAL; SET C.ENROLL; RUN; 

%MACRO FLOWCHART(I);
PROC SQL; 
CREATE TABLE C.FINAL AS SELECT * FROM C.FINAL 
WHERE EXC&I. NE 1;
QUIT;

PROC SQL; SELECT COUNT(DISTINCT INDI_DSCM_NO) AS CNT FROM C.FINAL; QUIT;
%MEND; 
%FLOWCHART(1); %FLOWCHART(2);  %FLOWCHART(3); %FLOWCHART(4); %FLOWCHART(5); %FLOWCHART(6); %FLOWCHART(7);  %FLOWCHART(9); 

PROC FREQ DATA=C.FINAL; TABLE COL_ONCE COL_90; RUN; 

*Non user matched to colchicine user - once;
ods output StdDiff = C.PSM_RST1;
PROC PSMATCH DATA =C.FINAL REGION = ALLOBS; 
CLASS COL_ONCE sex  AGE_GR cvd3 como2 como3 como9 como10 como12 como13;
PSMODEL COL_ONCE(TREATED='1') = AGE_GR sex  cvd3 como2 como3 como9 como10 como12 como13; 
MATCH METHOD = GREEDY(K=1) STAT =LPS CALIPER =0.2 ; 
ASSESS PS VAR= (age_gout sex income cci cvd: como: lab: MEDI:);
OUTPUT OUT(OBS=MATCH)=C.PSM1 MATCHID = _MATCHID; 
RUN; 

data entire; set c.psm_rst1; if Obs = "All"; run; 
data psm; set c.psm_rst1; if Obs = "Matched"; run; 

/*Non user matched to colchicine user - over 90 days;*/
DATA C.FINAL9; SET C.FINAL; 
IF COL_90 NE 1 AND COL_ONCE = 1 THEN EXC8 = 1; ELSE EXC8 = 0; 
IF EXC8 NE 1; RUN;

ods output StdDiff = C.PSM_RST9;
PROC PSMATCH DATA =C.FINAL9 REGION = ALLOBS; 
CLASS COL_90 sex cvd1 cvd3 como2 como3 como9 como10 como12 como13;
PSMODEL COL_90(TREATED='1') = age_gout sex cvd1 cvd3 como2 como3 como9 como10 como12 como13; 
MATCH METHOD = GREEDY(K=1) STAT =LPS CALIPER =0.2 ; 
ASSESS PS VAR= (age sex income cci cvd: como: lab: MEDI:);
OUTPUT OUT(OBS=MATCH)=C.PSM9 MATCHID = _MATCHID; 
RUN; 

/*Cox model*/
/*Table 2*/
%macro outfreq(data);
data base; set &data.;
group = COL_ONCE; run; 

%do i = 1 %to 7; 
ods output CrossTabFreqs=table&i;
ods output chisq=CHISQ&i;
proc freq data=base;
table out&i. * group / nopercent norow chisq; quit;

data table&i.; set table&i.; 
if out&i. ne 0; 
if group = 1 or group =0;
if _type_ = "11";
run; 

proc sort data=table&i.; by group; run; 
proc transpose data = table&i. out= tab2_freq&i.;
var Frequency;
by out&i.; 
run; 

proc sql; 
create table tab2_freq&i. as select &i. as order, col1 as non, col2 as user
from tab2_freq&i.;
quit;
%end;
%mend;
%outfreq(c.final);
%outfreq(c.final9);
%outfreq(c.psm9);
%outfreq(c.psm1);

data table2; set tab2_:; run; 
proc sort data=table2; by order; run; 

*Table 2 - HR; 
%MACRO HR(data); 
*group, data 지정;
data base; set &data.;
GROUP = COL_90; run; 

%DO I = 1 %TO 7;
*Before matching;
ODS OUTPUT PARAMETERESTIMATES=SET_&I.;
PROC PHREG DATA=base nosummary; 
CLASS GROUP(REF = "0")/PARAM=REFERENCE;
MODEL TDUR&I.*OUT&I.(0)=GROUP /RL; *Ref: Non user;
RUN;

DATA SET_&I.; SET SET_&I.; 
IF PARAMETER = "GROUP";
OUTCOME = &I.;
HR=ROUND(HazardRatio,0.01);
UCI=ROUND(HRUpperCL,0.01);
LCI=ROUND(HRLowerCL,0.01); 
A=CAT(HR,"(",LCI,"-",UCI,")");
RUN; 

PROC SQL; 
CREATE TABLE TAB2HR_&I. AS SELECT &I. AS ORDER, OUTCOME, A, ProbChiSq, PARAMETER
FROM SET_&I.;
QUIT; 
%END;
%MEND;
%HR(c.final); data TAB2HR; SET TAB2HR_:; RUN; 
%HR(c.final9); data TAB2HR; SET TAB2HR_:; RUN; 

*Table 2 - after psm HR; 
%MACRO HR(data); 
*group, data 지정;
data base; set &data.;
GROUP = COL_ONCE; run; 

%DO I = 1 %TO 7;
ODS OUTPUT PARAMETERESTIMATES=SET_&I.;
PROC PHREG DATA=BASE nosummary; 
CLASS GROUP(REF = "0")/PARAM=REFERENCE;
MODEL TDUR&I.*OUT&I.(0)=GROUP /RL; *Ref: Non user;
STRATA _MATCHID;
RUN;

DATA SET_&I.; SET SET_&I.; 
IF PARAMETER = "GROUP";
OUTCOME = &I.;
HR=ROUND(HazardRatio,0.01);
UCI=ROUND(HRUpperCL,0.01);
LCI=ROUND(HRLowerCL,0.01); 
A=CAT(HR,"(",LCI,"-",UCI,")");
RUN; 

PROC SQL; 
CREATE TABLE TAB2HR_&I. AS SELECT &I. AS ORDER, OUTCOME, A, ProbChiSq, PARAMETER
FROM SET_&I.;
QUIT; 
%END;
%MEND;
%HR(C.PSM1);

DATA TAB2_PSMRST; SET TAB2HR_:; RUN; 

